DemoTreeNode/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('streeApp.urls', namespace='blog')),

]

streeApp/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.createPost, name='createPost'),
    path('update/', views.updatePost, name='updatePost'),
    path('update/<int:edit_id>', views.edit, name='edit'),

]

streeApp/models.py
from django.db import models

from mptt.models import MPTTModel, TreeForeignKey


class Tags(MPTTModel):
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['id']

    def __str__(self):
        return self.name

    # class Meta:
    #     db_table = 'tags'

class Posts(models.Model):
    title = models.CharField(max_length=250)
    detail = models.TextField(null=True)
    tags = models.ManyToManyField(Tags)

    def __str__(self):
        return self.title

    # class Meta:
    #     db_table = 'posts'

streeApp/forms.py
from django import forms
from .models import Tags, Posts
from mptt.forms import TreeNodeChoiceField

class NewPostForm(forms.ModelForm):
    class Meta:
        model = Posts
        #fields = '__all__'
        fields = ('title', 'detail')
        widgets = {
            'detail': forms.Textarea(attrs={'class': 'col-md-8 '}),
        }

class UpdatePostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = '__all__'
        #fields = ('title', 'detail')
        widgets = {
            'detail': forms.Textarea(attrs={'class': 'col-md-8  '}),
        }

class NewTagsForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Tags.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update(
            {'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Tags
        fields = ('name', 'parent')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'col-sm-12'}),
        }

    def save(self, *args, **kwargs):
        Tags.objects.rebuild()
        return super(NewTagsForm, self).save(*args, **kwargs)

streeApp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect

from .models import Posts, Tags
from .forms import NewTagsForm , NewPostForm , UpdatePostForm
# Create your views here.

def createPost(request):
    tags = Tags.objects.all()
    post_form = NewPostForm(request.POST or None)
    tag_form = NewTagsForm(request.POST or None)

    if post_form.is_valid():
        if request.method == 'POST':
            tag_data = request.POST.get('tags')
            print("::::::::::::::::", len(tag_data))

            if len(tag_data)!=0:
                tag_data = (request.POST.get('tags')).split(',')

                tag_data = list(map(int, tag_data))
                title = post_form.cleaned_data['title']
                detail = post_form.cleaned_data['detail']

                posts_add = Posts.objects.create(
                    title = title,
                    detail = detail,
                )
                for x in tag_data:
                    posts_add.tags.add(Tags.objects.get(id=x))


        # post_form.save()
        return HttpResponseRedirect(request.path_info)

    if tag_form.is_valid():
        tag_form.save()
        return HttpResponseRedirect(request.path_info)

    context = {'post_form': post_form,'tags': tags}
    template = 'pages/create_blog.html'
    return render(request, template, context)



def updatePost(request):
    posts = Posts.objects.all()
    tags = Tags.objects.all()
    tag_form = NewTagsForm(request.POST or None)
    post_form = NewPostForm(request.POST or None)
    update_form = UpdatePostForm(request.POST or None)

    post_id = request.POST.get('post_id')
    post_idd = 29
    # print("::::::::::::::::",post_id,type(post_id))
    if post_id == str(post_id) and len(post_id) !=0 :
        post_idd = int(post_id)
        print("::::::::::::::::", post_idd, type(post_idd))

    edit_post = get_object_or_404(Posts, pk=post_idd)  # (model,pk)
    form = UpdatePostForm(instance=edit_post)

    if request.method == "POST":
        form = UpdatePostForm(request.POST, instance=edit_post)
        if form.is_valid():
            form.save()
            # return redirect('/')


    if tag_form.is_valid():
        tag_form.save()
        return HttpResponseRedirect(request.path_info)

    if request.method == 'POST':
        tag_data = request.POST.get('tags')
        # print("::::::::::::::::",type(tag_data))
        if tag_data == str(tag_data):
            tag_data = (request.POST.get('tags')).split(',')
            tag_data = list(map(int, tag_data))
            # print("::::::::::::::::",tag_data)
            for x in tag_data:
                posts = posts.filter(tags__id__exact=x)
                print("------------------", posts)

    context = {'tags': tags, 'posts':posts , 'update_form':update_form, 'form': form}

    template = 'pages/update_blog.html'
    return render(request, template, context)


def edit(request, edit_id):
    # if page not available then show 404 29
    edit_post = get_object_or_404(Posts, pk=edit_id)  # (model,pk)
    form = UpdatePostForm(instance=edit_post)

    if request.method == "POST":
        # print("printing post : ",request.POST)
        form = UpdatePostForm(request.POST, instance=edit_post)
        if form.is_valid():
            form.save()
            # return redirect('/')

    context = {'form':form}
    template_name = 'pages/edit_blog.html'
    return render(request,template_name, context)

streeApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/tree_view.css' %}">
    <link rel="stylesheet" href="{% static 'css/update_view.css' %}">







</head>
<body>

{% include 'partials/navbar.html' %}

{% block content %}

{% endblock %}

</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{% static 'js/tree_view.js' %}"></script>
<script src="{% static 'js/update_view.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"
          integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
            crossorigin="anonymous"></script>

</html>

streeApp/templates/pages/create_blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {# <----------create a post------------>#}



    <br>
    <br>
    <br>


    <div class="container">
        <div class="row">

            <div class="col-xs-12 col-sm-6">
                <div class="box">

                    <form method="post">
                        {% csrf_token %}
                        {{ post_form.as_p }}
                        {#              <p id="valueList" name="tags"></p>#}
                        <input type="hidden" id="tagss" name="tags" value=""></input>
                        <p>Must be choose at least 1 tag to create post never create</p>
                        <input type="submit" value="Save">
                    </form>

                </div>
            </div>

            <div class="col-xs-12 col-sm-6">
                <div class="box">

                    {#      _________________________________________tag#}

                    {% load mptt_tags %}


                    {#<ul class="root" >#}
                    {#    {% recursetree tags %}#}
                    {#        <li id="{{ node.id }}" class="caret">#}
                    {##}
                    {#            <input type="checkbox" id="valueList" name="{{ node.name }}" value="{{ node.id }}" class="checkbox">#}
                    {#            {{ node.level }} {{ node.name }}{{ node.id }}#}
                    {#            <button class="btn"  onclick="myFunction({{ node.id }})"><i class="fa fa-plus"></i></button>#}
                    {##}
                    {#            {% if not node.is_leaf_node %}#}
                    {#                <ul class="children nested">#}
                    {#                    {{ children }}#}
                    {#                </ul>#}
                    {#            {% endif %}#}
                    {#        </li>#}
                    {#    {% endrecursetree %}#}
                    {#</ul>#}



                    {% recursetree tags %}

                        <div id="{{ node.id }}">
                            <input type="checkbox" id="valueList" name="{{ node.name }}" value="{{ node.id }}"
                                   class="checkbox">
                            {{ node.name }}
                            <button class="btn" onclick="myFunction({{ node.id }})"><i class="fa fa-plus"></i></button>
                        </div>


                        {% if not node.is_leaf_node %}
                            <div class="children" style="padding-left: 20px">
                                {{ children }}
                            </div>
                        {% endif %}

                    {% endrecursetree %}


                    <script>

                        {#checkbox#}
                        var valueList = document.getElementById('valueList');
                        var text = '<span > Tags : </span>';
                        var listArray = []

                        var checkboxes = document.querySelectorAll('.checkbox');

                        for (var checkbox of checkboxes) {
                            checkbox.addEventListener('click', function () {
                                if (this.checked == true) {
                                    console.log(this.value);
                                    console.log(this.name);
                                    listArray.push(this.value);
                                    valueList.innerHTML = listArray.join(',');
                                } else {
                                    console.log('unchecked')
                                    listArray = listArray.filter(e => e !== this.value);
                                    valueList.innerHTML = listArray.join(',');
                                }
                                {#console.log(valueList)#}
                                console.log(listArray)
                                document.getElementById("tagss").value = listArray

                            })
                        }


                        function formExit() {
                            document.getElementById("newForm").remove();
                        }

                        function myFunction(id) {
                            if (document.contains(document.getElementById("newForm"))) {
                                document.getElementById("newForm").remove();
                            }

                            var d1 = document.getElementById(id);
                            d1.insertAdjacentHTML('afterend',
                                '<form id="newForm" class="form-insert py-2" method="post"> \
                                          <div class="d-flex justify-content-between"> \
                                          <div><button type="submit" class="btn"><i class="fa fa-check"></i></button>      <button type="button" class="btn" onclick="formExit()""><i class="fa fa-times"></i></button></div></div> \
                                          <input type="text" name="name" placeholder="add new tag" class="col-sm-12" maxlength="50" required="" id="id_name"> \
                                          <select name="parent" class="d-none" id="id_parentt"> \
                                          <option value="' + id + '" selected="' + id + '"></option> \
                </select> \
                {% csrf_token %} \
              </form>');

                            //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
                        }

                        $('#myForm').trigger("reset");
                    </script>


                    {# ____________________________________________________tag#}
                </div>
            </div>

        </div>
    </div>




{% endblock %}

streeApp/templates/pages/edit_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

                <form  method="POST">
                    {% csrf_token %}

                    {{ form.as_p }}

                    <input type="submit" name="Submit">
                </form>

</body>
</html>

streeApp/templates/pages/update_blog.html
{% extends 'base.html' %}

{% block content %}

    {# <----------update a post------------>#}



    <br>
    <br>
    <br>


    <div class="container">
        <div class="row">

            <div class="col-xs-12 col-sm-6">
                <div class="box">

                <p>Without ajax can not complete inpage update on Templating</p>

                    <div id="demo" class="collapse">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" name="Submit">
                        </form>

                    </div>
                <form method="POST">
                        {% csrf_token %}
                        <input type="hidden" id="post_id" name="post_id"></input>
                    {% for post in posts %}
                        <a href="{{ post.id }}">{{ post.title }}</a>

                        <button class="btn" type="submit" data-toggle="collapse" data-target="#demo"
                                onclick="menuCollapse('{{ post.id }}')">{{ post.title }}</button>

                        <br>
                    {% endfor %}
                </form>

{#                    <form method="POST">#}
{#                        {% csrf_token %}#}
{#                        <input type="hidden" id="post_id" name="post_id"></input>#}
{#                        <input type="submit" value="Search">#}
{##}
{#                    </form>#}


                </div>
            </div>

            <div class="col-xs-12 col-sm-6">
                <div class="box">

                    <form method="post">
                        {% csrf_token %}

                        <input type="hidden" id="tagss" name="tags" value=""></input>

                        <input type="submit" value="Search">
                    </form>

                    {#      _________________________________________tag#}

                    {% load mptt_tags %}


                    {% recursetree tags %}

                        <div id="{{ node.id }}">
                            <input type="checkbox" id="valueList" name="{{ node.name }}" value="{{ node.id }}"
                                   class="checkbox">
                            {{ node.name }}
                            <button class="btn" onclick="myFunction({{ node.id }})"><i class="fa fa-plus"></i></button>
                        </div>
                        {#          <label for="{{ node.id }}"> {{ node.name }} </label><br>#}



                        {% if not node.is_leaf_node %}
                            <div class="children" style="padding-left: 20px">
                                {{ children }}
                            </div>
                        {% endif %}

                    {% endrecursetree %}


                    <script>

                        {#checkbox#}
                        var valueList = document.getElementById('valueList');
                        var text = '<span > Tags : </span>';
                        var listArray = []

                        var checkboxes = document.querySelectorAll('.checkbox');

                        for (var checkbox of checkboxes) {
                            checkbox.addEventListener('click', function () {
                                if (this.checked == true) {
                                    console.log(this.value);
                                    console.log(this.name);
                                    listArray.push(this.value);
                                    valueList.innerHTML = listArray.join(',');
                                } else {
                                    console.log('unchecked')
                                    listArray = listArray.filter(e => e !== this.value);
                                    valueList.innerHTML = listArray.join(',');
                                }
                                {#console.log(valueList)#}
                                console.log(listArray)
                                document.getElementById("tagss").value = listArray

                            })
                        }


                        function formExit() {
                            document.getElementById("newForm").remove();
                        }

                        function myFunction(id) {
                            if (document.contains(document.getElementById("newForm"))) {
                                document.getElementById("newForm").remove();
                            }

                            var d1 = document.getElementById(id);
                            d1.insertAdjacentHTML('afterend',
                                '<form id="newForm" class="form-insert py-2" method="post"> \
                                          <div class="d-flex justify-content-between"> \
                                          <div><button type="submit" class="btn"><i class="fa fa-check"></i></button>      <button type="button" class="btn" onclick="formExit()""><i class="fa fa-times"></i></button></div></div> \
                                          <input type="text" name="name" placeholder="add new tag" class="col-sm-12" maxlength="50" required="" id="id_name"> \
                                          <select name="parent" class="d-none" id="id_parentt"> \
                                          <option value="' + id + '" selected="' + id + '"></option> \
                </select> \
                {% csrf_token %} \
              </form>');

                            //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
                        }


                        $('#myForm').trigger("reset");

                        function menuCollapse(post) {
                            {#console.log(post);#}

                            document.getElementById("post_id").value = post

                        }


                    </script>

                </div>
            </div>

        </div>
    </div>




{% endblock %}

streeApp/templates/partials/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Demo_Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'blog:createPost' %}">Create Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:updatePost' %}">Update Post</a>
        </li>
      </ul>
    </div>
  </div>
</nav>